apiVersion: v2
name: orders
description: A Helm chart for the Retail Store Sample App Orders Microservice
type: application

# This is the chart version. This version number should be incremented each time you make changes to the chart.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be incremented each time you make changes to the application source code.
appVersion: "1.16.0"
