# Default values for orders mock service.
replicaCount: 1

image:
  # Swapping out the heavy Java app for a lightweight Go web server
  repository: hashicorp/http-echo
  pullPolicy: IfNotPresent
  tag: "0.2.3"

service:
  type: ClusterIP
  port: 8080

# Extremely small boundaries since Go binaries require almost zero overhead
resources:
  limits:
    cpu: 100m
    memory: 32Mi
  requests:
    cpu: 10m
    memory: 16Mi

nodeSelector: {}
tolerations: []
affinity: {}
