apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: catalog

  template:
    metadata:
      labels:
        app: catalog

    spec:
      containers:
      - name: catalog

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.service.port }}

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}

          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
